language: node_js
node: 14
git:
  depth: 3
cache: yarn
before_script:
  - yarn workspace @trulyacerbic/ttt-apis build
jobs:
  - stage: test
    name: Testing gmaster
    script: yarn workspace gmaster test --runInBand

  - stage: test
    name: Testing ghost
    script: yarn workspace ghost test --runInBand

  - stage: deploy
    name: Deploying Docker containers
    if: branch = master
    cache:
      directories:
        - $HOME/docker
    install: skip
    services:
      - docker
    before_script: skip
    script: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deployment/travisci/travis_build_docker.sh; fi
    before_deploy:
      # populate known_hosts with target host fingerprint
      - echo "$DOCKER_DEPLOY_KNOWN_HOST_BASE64" | base64 -d >> $HOME/.ssh/known_hosts
      # add ssh public key for the ssh user
      - echo "$DOCKER_DEPLOY_RSA_KEY_BASE64" | base64 -d > /tmp/deploy_rsa
      - eval "$(ssh-agent -s)"
      - chmod 600 /tmp/deploy_rsa
      - ssh-add /tmp/deploy_rsa
    deploy:
      provider: script
      skip_cleanup: true
      script: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deployment/travisci/travis_deploy_docker.sh; fi

  - stage: deploy
    name: Deploying Next.js Client code
    install: skip
    before_script: npm i -g vercel
    script:
      - bash ./deployment/travisci/travis_deploy_client.sh
