language: node_js
node: 14
git:
    depth: 3
cache: yarn
before_script:
    - yarn workspace @trulyacerbic/ttt-apis build
jobs:
    - stage: test
      name: Testing gmaster
      script: yarn workspace gmaster test

    - stage: test
      name: Testing ghost
      script: yarn workspace ghost test

    - stage: deploy
      if: branch = master
      cache: false
      install: skip
      services:
          - docker
      before_script: skip
      script:
          - bash ./deployment/travis_build_push.sh
