language: node_js
node: 14
git:
    depth: 3
branches:
    #whitelist
    only: master
cache: yarn
before_script:
    - yarn workspace @trulyacerbic/ttt-apis build
jobs:
    - stage: test
      name: Testing gmaster
      script: yarn workspace gmaster test
    - stage: test
      name: Testing ghost
      script: yarn workspace ghost test
    - stage: test
      script: echo "Secret: $DOCKER_REGISTRY_ADDR"
    - stage: deploy
      services:
          - docker
      script:
          - docker -v
