language: node_js
node: 14
git:
  depth: 3
cache: yarn
before_script:
  - yarn workspace @trulyacerbic/ttt-apis build
jobs:
  - stage: test
    name: Testing gmaster
    script: yarn workspace gmaster test --runInBand

  - stage: test
    name: Testing ghost
    script: yarn workspace ghost test --runInBand

  - &deploy
    stage: deploy
    name: Deploying Docker containers
    if: branch = master
    cache: false
    install: skip
    services:
      - docker
    before_script: skip
    script: if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./deployment/travis_build_push.sh; fi

  - <<: *deploy
    name: Deploying Next.js Client code
    services:
    if:
    before_script: npm i -g now
    script:
      - bash ./deployment/travis_deploy_client.sh
