yarnPath: ".yarn/releases/yarn-berry.cjs"
pnpMode: loose
pnpFallbackMode: all

packageExtensions:
  ws@*:
    dependencies:
      bufferutil: "*"
      utf-8-validate: "*"
  debug@*:
    dependencies:
      supports-color: "*"

  # declare peer and optional dependenciess to be direct deps
  # to avoid Berry nagging
  "@graphql-inspector/commands@2.3.0":
    dependencies:
      "@graphql-inspector/config": "2.3.0"
      "@graphql-inspector/loaders": "2.3.0"
      "yargs": "16.1.0"

  "@graphql-inspector/loaders@2.3.0":
    dependencies:
      "@graphql-inspector/config": "2.3.0"
      "@graphql-tools/utils": "^6.0.0 || ^7.0.0"
