packageExtensions:
  "@graphql-inspector/commands@2.3.0":
    dependencies:
      "@graphql-inspector/config": 2.3.0
      "@graphql-inspector/loaders": 2.3.0
      yargs: 16.1.0
  "@graphql-inspector/loaders@2.3.0":
    dependencies:
      "@graphql-inspector/config": 2.3.0
      "@graphql-tools/utils": ^6.0.0 || ^7.0.0
  debug@*:
    dependencies:
      supports-color: "*"
  ws@*:
    dependencies:
      bufferutil: "*"
      utf-8-validate: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-production-install.cjs
    spec: "https://gitlab.com/Larry1123/yarn-contrib/-/raw/master/packages/plugin-production-install/bundles/@yarnpkg/plugin-production-install.js"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-berry.cjs
