version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  gmaster:
    image: gmaster:latest
    restart: always
  ghost:
    image: ghost:latest
    restart: always
    ports:
    - "3060:3060"
  deployer:
    image: deployer:latest
    restart: on-failure
    depends_on:
    - prisma
volumes:
  mysql: