version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

  deployer:
    build:
      context: ./gamesdb
      dockerfile: Dockerfile
      args:
        PRISMA_PORT: 4466
    image: deployer:latest
    restart: on-failure
    depends_on:
    - prisma

  gmaster:
    build:
      context: ./gmaster
      dockerfile: Dockerfile
    image: gmaster:latest
    restart: always

  ghost:
    build:
      context: ./ghost
      dockerfile: Dockerfile
    image: ghost:latest
    restart: always
    command: node --inspect=0.0.0.0 index.js
    ports:
    - "3060:3060"
    - "9229:9229"

volumes:
  mysql: