version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.29.1
    restart: always
    depends_on:
      - mysql
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql

  deployer:
    build:
      dockerfile: deployer.Dockerfile
      context: .
      args:
        PRISMA_PORT: 4466
    image: deployer:latest
    restart: on-failure
    depends_on:
      - prisma

  gmaster:
    build:
      context: .
      dockerfile: gmaster.Dockerfile
    image: gmaster:latest
    restart: always

  ghost:
    build:
      context: .
      dockerfile: ghost.Dockerfile
    image: ghost:latest
    restart: always
    # command: node --inspect=0.0.0.0 index.js
    ports:
      - "3060:3060"
      - "9229:9229"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    image: tttclient:latest
    restart: always
    ports: 
      - "3030:3030"

volumes:
  mysql: