version: "3"
services:
    prisma:
        image: prismagraphql/prisma:1.29.1
        restart: always
        depends_on:
            - mysql
        environment:
            PRISMA_CONFIG: |
                port: 4466
                databases:
                  default:
                    connector: mysql
                    host: mysql
                    port: 3306
                    user: root
                    password: prisma
                    migrations: true

    mysql:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: prisma
        volumes:
            - mysql:/var/lib/mysql

    prisma-deployer:
        build:
            dockerfile: deployment/prisma-deployer.Dockerfile
            context: ..
            args:
                PRISMA_HOSTPORT: prisma:4466
        image: prisma-deployer:latest
        restart: on-failure
        depends_on:
            - prisma

    gmaster:
        build:
            dockerfile: deployment/gmaster.Dockerfile
            context: ..
            args:
                GMASTER_PORT: 3000
        image: gmaster:latest
        environment:
            PRISMA_URL: http://prisma:4466
        restart: always

    ghost:
        build:
            dockerfile: deployment/ghost.Dockerfile
            context: ..
            args:
                GHOST_PORT: 3060
        image: ghost:latest
        environment:
            PRISMA_URL: http://prisma:4466
            GMASTER_URI: gmaster:3000
        restart: always
        # command: node --inspect=0.0.0.0 index.js
        ports:
            - "3060:3060"
            - "9229:9229"

    client:
        build:
            dockerfile: deployment/client.Dockerfile
            context: ..
            args:
                CLIENT_PORT: 3030
        image: tttclient:latest
        environment:
            # so, in principle ghost server can be anywhere independent of
            # client server, thus we need to point to it explicitly for runtime
            GHOST_URL: http://localhost:3060
        restart: always
        ports:
            - "3030:3030"

volumes:
    mysql:
