version: "3.6"
services:
    postgres:
        image: postgres:12
        restart: always
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgrespassword
    graphql-engine:
        image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
        volumes:
            - ../packages/gamesdb/hasura/migrations:/hasura-migrations
            - ../packages/gamesdb/hasura/metadata:/hasura-metadata
        ports:
            - "8080:8080"
        depends_on:
            - "postgres"
        restart: always
        environment:
            HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
            HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
            HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
            ## uncomment next line to set an admin secret
            # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    # prisma-deployer:
    #     build:
    #         dockerfile: deployment/prisma-deployer.Dockerfile
    #         context: ..
    #         args:
    #             PRISMA_HOSTPORT: prisma:4466
    #     image: prisma-deployer:latest
    #     restart: on-failure
    #     depends_on:
    #         - prisma

volumes:
    db_data:
