version: "3"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    build:
      dockerfile: ../../deployment/hasura-migrations.Dockerfile
      context: ../packages/gamesdb
    image: ttt/hasura:latest
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey

  gmaster:
    build:
      dockerfile: deployment/gmaster.Dockerfile
      context: ..
      args:
        GMASTER_PORT: 3000
    image: ttt/gmaster:latest
    environment:
      HASURA_URL: http://graphql-engine:8080/v1/graphql
    restart: always

  ghost:
    build:
      dockerfile: deployment/ghost.Dockerfile
      context: ..
      args:
        GHOST_PORT: 3060
    image: ttt/ghost:latest
    environment:
      GMASTER_URL: http://gmaster:3000
      JWT_SECRET:
    restart: always
    ports:
      - "3060:3060"
      - "9229:9229"

  client:
    build:
      dockerfile: deployment/client.Dockerfile
      context: ..
      args:
        CLIENT_PORT: 3030
    image: ttt/client:latest
    environment:
      # so, in principle ghost server can be anywhere independent of
      # client server, thus we need to point to it explicitly for runtime
      GHOST_URL: http://localhost:3060
    restart: always
    ports:
      - "3030:3030"

volumes:
  db_data_dev:
